# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 14:38
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wurst', '0003_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('type',))),
                ('verbs', models.TextField(blank=True)),
                ('from_any_status', models.BooleanField(default=False)),
                ('initial', models.BooleanField(default=False)),
                ('from_statuses', models.ManyToManyField(blank=True, related_name='from_transitions', to='wurst.Status')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_transitions', to='wurst.Status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wurst.IssueType')),
            ],
        ),
    ]
